"""empty message

Revision ID: 25279a0b5c75
Revises: d4145790eaa3
Create Date: 2016-11-01 23:52:04.261241

"""

# revision identifiers, used by Alembic.
revision = '25279a0b5c75'
down_revision = 'd4145790eaa3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('van', sa.String(length=255), nullable=True))
    op.drop_column('user', 'twilio_accounts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twilio_accounts', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user', 'van')
    ### end Alembic commands ###
