"""empty message

Revision ID: 62e58bbe9535
Revises: e614cb2b9e6b
Create Date: 2016-10-21 14:51:18.352200

"""

# revision identifiers, used by Alembic.
revision = '62e58bbe9535'
down_revision = 'e614cb2b9e6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('on_shift', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'on_shift')
    ### end Alembic commands ###
