"""empty message

Revision ID: 785cf01fb324
Revises: b7c0cfa43719
Create Date: 2016-11-02 00:34:27.892622

"""

# revision identifiers, used by Alembic.
revision = '785cf01fb324'
down_revision = 'b7c0cfa43719'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twilio', sa.Column('is_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twilio', 'is_active')
    ### end Alembic commands ###
