"""empty message

Revision ID: bbc53947eabb
Revises: None
Create Date: 2016-10-27 15:19:40.050634

"""

# revision identifiers, used by Alembic.
revision = 'bbc53947eabb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('region', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('van_confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'van_confirmed')
    op.drop_column('user', 'region')
    ### end Alembic commands ###
