"""empty message

Revision ID: e2225cf1af9f
Revises: a44f5481662b
Create Date: 2016-10-21 10:49:43.134407

"""

# revision identifiers, used by Alembic.
revision = 'e2225cf1af9f'
down_revision = 'a44f5481662b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shift', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('van', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'van')
    op.drop_column('user', 'shift')
    ### end Alembic commands ###
