"""empty message

Revision ID: e614cb2b9e6b
Revises: e2225cf1af9f
Create Date: 2016-10-21 11:48:10.102527

"""

# revision identifiers, used by Alembic.
revision = 'e614cb2b9e6b'
down_revision = 'e2225cf1af9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temp_pass', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temp_pass')
    ### end Alembic commands ###
